const assert=require('node:assert/strict');
const M=require('./expense-model.js');
const headers=['Festival','Expense','Item','Amount','Paid On'];
const amounts=[1200,140,240,450,140,1420,450,11180,400,10000,915,180,2000,430,2150];
const rows=amounts.map((n,i)=>[i<7?'Janmashtami':'Ganpati',i===0?'Dahi Handi':i===7?'Decoration':'','Item '+i,n,i<7?'05/09':'15/08']);
const payload=(r)=>({ok:true,collection:597188,defaultYear:2026,sheets:[{rows:r}]});
const sample=M.parse(payload([headers,...rows]));
assert.equal(sample.expensePaise,3129500);assert.equal(sample.balancePaise,56589300);
assert.equal(sample.records[14].category,'Decoration');
const reordered=[headers,...rows].map(r=>[r[4],'',r[2],r[0],r[3],r[1]]);
assert.deepEqual(M.parse(payload([[],[],...reordered])).records.map(r=>[r.item,r.amountPaise,r.date]),sample.records.map(r=>[r.item,r.amountPaise,r.date]));
assert.equal(M.parse(payload([headers,...rows,['Holi','','New',-0.25,'01/03/2027']])).expensePaise,3129475);
assert.equal(M.parse(payload([headers,...rows,['Holi','','New',0,'']])).records.at(-1).category,'Uncategorised');
assert.equal(M.money('5,97,188.25'),59718825);assert.equal(M.money('0.01'),1);
for(const bad of ['', 'abc','12oops','1,2','1.234','#REF!']) assert.throws(()=>M.money(bad));
assert.throws(()=>M.parse(payload([headers,['Ganpati','','Item','','05/09']])));
assert.throws(()=>M.parse(payload([headers,['Ganpati','','Item',1,'31/02']])));
assert.throws(()=>M.parse(payload([headers,...rows,headers])));
assert.throws(()=>M.parse({...payload([headers,...rows]),collection:null}));
assert.equal(M.parse(payload([headers])).expensePaise,0);
assert.equal(M.date('2026-09-05',2026),'2026-09-05');
assert.equal(M.parse(payload([headers,...rows.slice(1)])).expensePaise,3009500);
console.log('PASS: sample totals, reordered/moved headers, additions/deletions, refunds, paise precision, category reset, empty table, invalid amounts/dates and ambiguous tables.');
const layout=M.parse(payload([headers,...rows,['Ganpati','','Banjo','',''],['Navratri','','','',''],['','','Total Expenses',123,''],['','','Total Collection',597188,'499933'],['','','A Wing',117500,'']]));
assert.equal(layout.expensePaise,3129500);assert.equal(layout.planned.length,1);
assert.equal(layout.planned[0].item,'Banjo');
assert.throws(()=>M.parse(payload([headers,['Ganpati','','Banjo','','2026-09-05']])));
console.log('PASS: planned items, festival placeholders, summary exclusion, and missing amounts with paid dates.');
