const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const front = { document: { addEventListener() {} } };
vm.createContext(front); vm.runInContext(fs.readFileSync('feta-registration.js', 'utf8'), front);
const good = {name:'कांतिलाल महाजन',whatsapp:'9403942777',flatNo:'1304',wing:'F',paid:'Yes'};
assert.equal(front.validateFeta(good), '');
assert.match(front.validateFeta({...good,paid:'No'}), /Please pay/);
for (const [field,value] of [['name','  '],['whatsapp','1234567890'],['flatNo','1305'],['flatNo','1401'],['wing','G'],['paid','']]) assert.ok(front.validateFeta({...good,[field]:value}));
let rows=[]; let now=Date.parse('2026-09-11T16:59:59+05:30');
const sheet={getLastRow:()=>rows.length,appendRow:r=>rows.push(r),getRange:()=>({createTextFinder:id=>({matchEntireCell:()=>({findNext:()=>rows.find(r=>r[0]===id)})})})};
const back={console,Date:class extends Date {static now(){return now}},ContentService:{MimeType:{JSON:'json'},createTextOutput:s=>({setMimeType:()=>JSON.parse(s)})},LockService:{getScriptLock:()=>({waitLock(){},hasLock:()=>true,releaseLock(){}})},PropertiesService:{getScriptProperties:()=>({getProperty:()=> 'sheet-id'})},SpreadsheetApp:{openById:()=>({getSheetByName:()=>sheet}),flush(){}},Utilities:{formatDate:()=> '2026-09-11 16:59:59'}};
vm.createContext(back); vm.runInContext(fs.readFileSync('feta-registration.gs','utf8'),back);
const parameter={...good,requestId:'12345678-1234-1234-1234-123456789abc'};
assert.equal(back.doPost({parameter:{...parameter,paid:'No'}}).status,'error');
assert.equal(rows.length,0);
assert.equal(back.doPost({parameter}).status,'success');
assert.equal(rows.length,2);
assert.equal(back.doPost({parameter}).status,'success'); assert.equal(rows.length,2);
now=Date.parse('2026-09-11T17:00:00+05:30');
assert.equal(back.doPost({parameter:{...parameter,requestId:'22345678-1234-1234-1234-123456789abc'}}).status,'error');
assert.equal(back.doPost({parameter}).status,'success');
assert.equal(back.doPost({parameter:{...parameter,wing:'G'}}).status,'error');
console.log('PASS: field validation, successful save, retry deduplication, exact IST cutoff, and server rejection.');
let initialize, refresh;
const handlers = {};
const paid = {value:'',addEventListener:(_, fn)=>{handlers.paid=fn;}};
const button = {disabled:false};
const elements = {fetaForm:{elements:{paid,flatNo:{add(){}}},addEventListener:(name,fn)=>{handlers[name]=fn;}},submitFeta:button,fetaDialog:{addEventListener(){}},fetaStatus:{},fetaSuccess:{},closeFeta:{addEventListener(){}}};
const ui = {document:{addEventListener:(_,fn)=>{initialize=fn;},getElementById:id=>elements[id],querySelectorAll:()=>[]},crypto:{randomUUID:()=>parameter.requestId},Option:function(){},setInterval:fn=>{refresh=fn;},Date:class extends Date{static now(){return now;}}};
vm.createContext(ui); vm.runInContext(fs.readFileSync('feta-registration.js','utf8'),ui);
const paymentAlerts = [];
ui.alert = message => paymentAlerts.push(message);
now=Date.parse('2026-09-10T12:00:00+05:30');
initialize(); assert.equal(button.disabled,true);
paid.value='No'; handlers.paid(); assert.equal(button.disabled,true);
assert.deepEqual(paymentAlerts, ['Please pay first.']);
paid.value='Yes'; handlers.paid(); assert.equal(button.disabled,false);
assert.equal(paymentAlerts.length, 1);
vm.runInContext('Date.now()',ui); refresh(); assert.equal(button.disabled,false);
paid.value='No'; handlers.paid(); refresh(); assert.equal(button.disabled,true);
now=Date.parse('2026-09-11T17:00:00+05:30');
paid.value='Yes'; handlers.paid(); assert.equal(button.disabled,true);
console.log('PASS: Save disabled for blank/unpaid, enabled for paid, and disabled at deadline.');
(async () => {
  const response = (body, ok=true) => ({ok,text:async()=>body});
  await assert.rejects(front.readFetaResponse(response('<html>Script function not found: doPost</html>')), /not configured/);
  await assert.rejects(front.readFetaResponse(response(JSON.stringify({status:'error',message:'Missing sheet configuration'}))), /Missing sheet configuration/);
  await assert.rejects(front.readFetaResponse(response('{"status":"success"}')), /incompatible/);
  assert.equal((await front.readFetaResponse(response('{"status":"success","registrationId":"saved-id"}'))).registrationId,'saved-id');
  console.log('PASS: HTML deployment errors, server errors, incompatible responses, and confirmed success.');
})().catch(error => { console.error(error); process.exitCode=1; });
