const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const front = { document: { addEventListener() {} } };
vm.createContext(front); vm.runInContext(fs.readFileSync('feta-registration.js', 'utf8'), front);
const good = {name:'कांतिलाल महाजन',whatsapp:'9403942777',flatNo:'1304',wing:'F',paid:'No'};
assert.equal(front.validateFeta(good), '');
for (const [field,value] of [['name','  '],['whatsapp','1234567890'],['flatNo','1305'],['flatNo','1401'],['wing','G'],['paid','']]) assert.ok(front.validateFeta({...good,[field]:value}));
let rows=[]; let now=Date.parse('2026-09-11T16:59:59+05:30');
const sheet={getLastRow:()=>rows.length,appendRow:r=>rows.push(r),getRange:()=>({createTextFinder:id=>({matchEntireCell:()=>({findNext:()=>rows.find(r=>r[0]===id)})})})};
const back={console,Date:class extends Date {static now(){return now}},ContentService:{MimeType:{JSON:'json'},createTextOutput:s=>({setMimeType:()=>JSON.parse(s)})},LockService:{getScriptLock:()=>({waitLock(){},hasLock:()=>true,releaseLock(){}})},PropertiesService:{getScriptProperties:()=>({getProperty:()=> 'sheet-id'})},SpreadsheetApp:{openById:()=>({getSheetByName:()=>sheet}),flush(){}},Utilities:{formatDate:()=> '2026-09-11 16:59:59'}};
vm.createContext(back); vm.runInContext(fs.readFileSync('feta-registration.gs','utf8'),back);
const parameter={...good,requestId:'12345678-1234-1234-1234-123456789abc'};
assert.equal(back.doPost({parameter}).status,'success');
assert.equal(rows.length,2);
assert.equal(back.doPost({parameter}).status,'success'); assert.equal(rows.length,2);
now=Date.parse('2026-09-11T17:00:00+05:30');
assert.equal(back.doPost({parameter:{...parameter,requestId:'22345678-1234-1234-1234-123456789abc'}}).status,'error');
assert.equal(back.doPost({parameter}).status,'success');
assert.equal(back.doPost({parameter:{...parameter,wing:'G'}}).status,'error');
console.log('PASS: field validation, successful save, retry deduplication, exact IST cutoff, and server rejection.');
(async () => {
  const response = (body, ok=true) => ({ok,text:async()=>body});
  await assert.rejects(front.readFetaResponse(response('<html>Script function not found: doPost</html>')), /not configured/);
  await assert.rejects(front.readFetaResponse(response(JSON.stringify({status:'error',message:'Missing sheet configuration'}))), /Missing sheet configuration/);
  await assert.rejects(front.readFetaResponse(response('{"status":"success"}')), /incompatible/);
  assert.equal((await front.readFetaResponse(response('{"status":"success","registrationId":"saved-id"}'))).registrationId,'saved-id');
  console.log('PASS: HTML deployment errors, server errors, incompatible responses, and confirmed success.');
})().catch(error => { console.error(error); process.exitCode=1; });
