(() => {
  const translations = {
    hi: {
      "Home": "होम", "Schedule": "कार्यक्रम", "Registration": "पंजीकरण", "Aarti": "आरती", "Accounts": "हिसाब", "Suggestions": "सुझाव", "Register": "पंजीकरण करें",
      "Notifications": "सूचनाएँ", "Mark all read": "सभी को पढ़ा हुआ चिह्नित करें", "Turn on browser alerts": "ब्राउज़र अलर्ट चालू करें", "Alerts appear while this site is open.": "यह साइट खुली होने पर अलर्ट दिखाई देंगे।",
      "Kurta registration started!": "कुर्ता पंजीकरण शुरू हो गया है!", "Event Registration will start soon!": "कार्यक्रम पंजीकरण जल्द शुरू होगा!", "Stay tuned for more updates!": "अधिक अपडेट के लिए जुड़े रहें!", "Loading today's event…": "आज का कार्यक्रम लोड हो रहा है…", "View today's schedule": "आज का कार्यक्रम देखें",
      "SAI VISTA CULTURAL COMMITTEE": "साई विस्टा सांस्कृतिक समिति", "Ganesh Festival": "गणेश उत्सव", "A celebration of devotion, culture, participation and community spirit.": "भक्ति, संस्कृति, सहभागिता और सामुदायिक भावना का उत्सव।", "Explore Festival": "उत्सव देखें", "Register for Events": "कार्यक्रमों के लिए पंजीकरण करें", "Festival begins in": "उत्सव शुरू होने में",
      "Full Festival Schedule": "पूरा उत्सव कार्यक्रम", "Close": "बंद करें", "SAI VISTA GANPATI 2026": "साई विस्टा गणपति 2026", "Ganpati Festival Kurta": "गणपति उत्सव कुर्ता", "Show your Ganpati spirit with the official Sai Vista Ganpati 2026 Kurta.": "आधिकारिक साई विस्टा गणपति 2026 कुर्ते के साथ गणपति उत्सव का जोश दिखाएँ।", "₹300 / Kurta": "₹300 / कुर्ता", "Sai Vista Ganpati 2026 Kurta": "साई विस्टा गणपति 2026 कुर्ता", "If you are interested in purchasing the festival Kurta, please complete the registration form below.": "यदि आप उत्सव का कुर्ता लेना चाहते हैं, तो नीचे दिया गया पंजीकरण फ़ॉर्म भरें।", "Per Kurta": "प्रति कुर्ता", "Registration deadline": "पंजीकरण की अंतिम तिथि", "Available sizes": "उपलब्ध साइज़", "Last date to register": "पंजीकरण की अंतिम तिथि", "8 September 2026": "8 सितंबर 2026", "Interested in getting a Kurta?": "क्या आप कुर्ता लेना चाहते हैं?", "Select your interest and size in the official registration form. Available sizes are S, M, L and XL.": "आधिकारिक पंजीकरण फ़ॉर्म में अपनी रुचि और साइज़ चुनें। उपलब्ध साइज़: S, M, L और XL।", "Important:": "महत्वपूर्ण:", "Kurta cost is": "कुर्ते की कीमत है", "Registration must be completed by": "पंजीकरण पूरा करने की अंतिम तिथि", "Register for Kurta ↗": "कुर्ते के लिए पंजीकरण करें ↗", "Pay ₹300 with UPI ↗": "UPI से ₹300 भुगतान करें ↗", "Choose your preferred UPI app next. ₹300 is prefilled—please verify the recipient and amount before approving payment.": "अगले चरण में अपना पसंदीदा UPI ऐप चुनें। ₹300 पहले से भरा है—भुगतान से पहले प्राप्तकर्ता और राशि जाँचें।", "Registration is managed through Google Forms.": "पंजीकरण Google Forms से संचालित है।",
      "LATEST UPDATE": "नवीनतम अपडेट", "Ganpati 2026 Event Schedule": "गणपति 2026 कार्यक्रम", "See the complete festival programme, important notes and registration information published by the Sai Vista Cultural Committee.": "साई विस्टा सांस्कृतिक समिति द्वारा प्रकाशित पूरा उत्सव कार्यक्रम, महत्वपूर्ण सूचनाएँ और पंजीकरण जानकारी देखें।", "View Full Schedule ↗": "पूरा कार्यक्रम देखें ↗", "Tap to enlarge": "बड़ा देखने के लिए टैप करें",
      "Festival Schedule": "उत्सव कार्यक्रम", "Events & activities": "कार्यक्रम और गतिविधियाँ", "Event Registration": "कार्यक्रम पंजीकरण", "Participate with us": "हमारे साथ भाग लें", "Aarti Nomination": "आरती नामांकन", "Choose your slot": "अपना स्लॉट चुनें", "Festival Accounts": "उत्सव हिसाब", "Transparent expenses": "पारदर्शी खर्च", "Ganpati Kurta": "गणपति कुर्ता", "Share a Suggestion": "सुझाव दें", "Help us make the festival better": "उत्सव को बेहतर बनाने में मदद करें", "Contact Us": "संपर्क करें", "Coordinators & website": "समन्वयक और वेबसाइट",
      "14 SEPTEMBER – 25 SEPTEMBER": "14 सितंबर – 25 सितंबर", "Ganpati 2026 Festival Schedule": "गणपति 2026 उत्सव कार्यक्रम", "Event dates and activities are based on the latest schedule shared by the Sai Vista Cultural Committee.": "कार्यक्रम की तिथियाँ और गतिविधियाँ साई विस्टा सांस्कृतिक समिति द्वारा साझा नवीनतम कार्यक्रम पर आधारित हैं।", "Add festival schedule to calendar": "उत्सव कार्यक्रम कैलेंडर में जोड़ें", "Downloads an .ics calendar file. Events are added as all-day reminders.": ".ics कैलेंडर फ़ाइल डाउनलोड होगी। कार्यक्रम पूरे दिन के रिमाइंडर के रूप में जुड़ेंगे।", "All days": "सभी दिन", "Highlights": "मुख्य आकर्षण", "Puja & Aarti": "पूजा और आरती", "Activities": "गतिविधियाँ",
      "OPENING DAY • MONDAY": "उद्घाटन दिवस • सोमवार", "Miravnuk • Lezim (TBD) • Ganesh Sthapana": "मिरवणूक • लेझीम (निर्धारित होना है) • गणेश स्थापना", "Miravnuk with music is planned between 3–7 PM. Residents are requested to plan decorations/work arrangements accordingly.": "संगीत के साथ मिरवणूक 3–7 PM के बीच प्रस्तावित है। निवासी सजावट/काम की व्यवस्था उसी अनुसार करें।", "TUESDAY": "मंगलवार", "WEDNESDAY": "बुधवार", "THURSDAY": "गुरुवार", "FRIDAY": "शुक्रवार", "SATURDAY": "शनिवार", "SUNDAY": "रविवार", "Housie": "हाउज़ी", "Community housie evening for Sai Vista residents.": "साई विस्टा निवासियों के लिए सामुदायिक हाउज़ी शाम।", "Games": "खेल", "Games and activities for residents.": "निवासियों के लिए खेल और गतिविधियाँ।", "Register →": "पंजीकरण करें →", "SPECIAL EVENT • FRIDAY": "विशेष कार्यक्रम • शुक्रवार", "Bollywood Night 🎬": "बॉलीवुड नाइट 🎬", "Music, dance, performances and entertainment.": "संगीत, नृत्य, प्रस्तुतियाँ और मनोरंजन।", "Drawing Competition • Talent Show 1": "चित्रकला प्रतियोगिता • टैलेंट शो 1", "Talent Show sessions are planned across the festival as announced by the committee.": "समिति की घोषणा के अनुसार टैलेंट शो के सत्र पूरे उत्सव में होंगे।", "Blood Donation • Treasure Hunt • Thali & Rangoli Competition • Fun N Fun Fair": "रक्तदान • ट्रेज़र हंट • थाली और रंगोली प्रतियोगिता • फन एन फन फेयर", "A full community activity day with multiple participation events.": "कई सहभागिता कार्यक्रमों के साथ पूरा सामुदायिक गतिविधि दिवस।", "View registrations →": "पंजीकरण देखें →", "Talent Show 2": "टैलेंट शो 2", "Second Talent Show session.": "टैलेंट शो का दूसरा सत्र।", "Fancy Dress": "फैंसी ड्रेस", "Fancy Dress is planned as a separate event.": "फैंसी ड्रेस अलग कार्यक्रम के रूप में आयोजित है।", "No activity currently planned": "फिलहाल कोई गतिविधि नियोजित नहीं है", "The programme will be updated if an activity is finalised.": "कोई गतिविधि तय होने पर कार्यक्रम अपडेट किया जाएगा।", "PUJA • THURSDAY": "पूजा • गुरुवार", "Satyanarayan Puja & Mahaprasad": "सत्यनारायण पूजा और महाप्रसाद", "Dedicated Satyanarayan Puja and Mahaprasad programme.": "समर्पित सत्यनारायण पूजा और महाप्रसाद कार्यक्रम।", "Open Puja registration →": "पूजा पंजीकरण खोलें →", "VISARJAN • FRIDAY": "विसर्जन • शुक्रवार", "Visarjan • Lezim (TBD) • DJ": "विसर्जन • लेझीम (निर्धारित होना है) • DJ", "Visarjan programme with evening DJ as noted in the latest festival schedule.": "नवीनतम कार्यक्रम के अनुसार शाम के DJ के साथ विसर्जन कार्यक्रम।", "📌 Important Notes": "📌 महत्वपूर्ण सूचनाएँ",
      "PARTICIPATE": "भाग लें", "Registration & Festival Forms": "पंजीकरण और उत्सव फ़ॉर्म", "Everything important is grouped in one place. Forms currently open inside a simple website modal so residents do not have to navigate away first.": "सभी महत्वपूर्ण फ़ॉर्म एक जगह हैं। फ़िलहाल फ़ॉर्म वेबसाइट के भीतर खुलते हैं ताकि निवासियों को तुरंत दूसरी जगह न जाना पड़े।", "MAIN REGISTRATION": "मुख्य पंजीकरण", "All Event Registration": "सभी कार्यक्रम पंजीकरण", "Use the common Sai Vista event registration form for festival activities.": "उत्सव गतिविधियों के लिए सामान्य साई विस्टा पंजीकरण फ़ॉर्म का उपयोग करें।", "Open Registration": "पंजीकरण खोलें", "Registration currently disabled": "पंजीकरण फिलहाल बंद है", "PUJA": "पूजा", "Satyanarayan Pooja": "सत्यनारायण पूजा", "Register for the Satyanarayan Pooja using the dedicated form.": "समर्पित फ़ॉर्म से सत्यनारायण पूजा के लिए पंजीकरण करें।", "Open Form": "फ़ॉर्म खोलें", "SPECIAL EVENT": "विशेष कार्यक्रम", "Participation and entry registration for Bollywood Night.": "बॉलीवुड नाइट में भाग लेने और प्रवेश के लिए पंजीकरण।", "PRASAD": "प्रसाद", "Satyanarayan Prasad Availability": "सत्यनारायण प्रसाद उपलब्धता", "Confirm availability / requirement for Satyanarayan Prasad.": "सत्यनारायण प्रसाद की उपलब्धता/आवश्यकता की पुष्टि करें।", "FUN FAIR": "फन फेयर", "Fun Fair Stall Entry": "फन फेयर स्टॉल प्रविष्टि", "Submit your Fun Fair stall event entry through the dedicated form.": "समर्पित फ़ॉर्म से अपने फन फेयर स्टॉल की प्रविष्टि भेजें।", "KURTA": "कुर्ता", "Kurta / Traditional Wear Registration": "कुर्ता / पारंपरिक पहनावा पंजीकरण", "Register for kurta orders / collection. This form opens in a dialog on the same page.": "कुर्ता ऑर्डर/कलेक्शन के लिए पंजीकरण करें। यह फ़ॉर्म इसी पेज पर खुलता है।", "Open Kurta Form": "कुर्ता फ़ॉर्म खोलें",
      "AUSPICIOUS MOMENT": "शुभ अवसर", "🪔 Ganesh Aarti Nomination": "🪔 गणेश आरती नामांकन", "Nominate yourself or your family for Ganesh Bappa's Aarti at Sai Vista.": "साई विस्टा में गणेश बप्पा की आरती के लिए स्वयं या परिवार का नाम दर्ज करें।", "Full Name *": "पूरा नाम *", "Flat Number *": "फ्लैट नंबर *", "Select Flat Number": "फ्लैट नंबर चुनें", "Wing *": "विंग *", "Select Wing": "विंग चुनें", "WhatsApp Number *": "व्हाट्सऐप नंबर *", "Enter 10 digits without country code.": "देश कोड के बिना 10 अंक दर्ज करें।", "Select Aarti Date *": "आरती की तिथि चुनें *", "Choose a date between 15 Sep and 24 Sep 2026.": "15 सितंबर और 24 सितंबर 2026 के बीच की तिथि चुनें।", "Select Slot *": "स्लॉट चुनें *", "Morning (8 AM)": "सुबह (8 AM)", "Evening (7:30 PM)": "शाम (7:30 PM)", "Select a date and slot to see current registrations.": "वर्तमान पंजीकरण देखने के लिए तिथि और स्लॉट चुनें।", "I will bring my own pooja thali and prasad": "मैं अपनी पूजा की थाली और प्रसाद लाऊँगा/लाऊँगी", "Submit Aarti Nomination": "आरती नामांकन भेजें", "Thank you for your nomination!": "आपके नामांकन के लिए धन्यवाद!", "ℹ️ Your nomination is sent to the Sai Vista festival registration system for coordination.": "ℹ️ आपका नामांकन समन्वय के लिए साई विस्टा उत्सव पंजीकरण प्रणाली को भेजा गया है।", "LIMITED REGISTRATION": "सीमित पंजीकरण",
      "TRANSPARENCY": "पारदर्शिता", "Festival Collection Dashboard": "उत्सव संग्रह डैशबोर्ड", "Live resident contribution status, grouped by wing. Select a wing in the chart to view its flats.": "विंग के अनुसार निवासियों के योगदान की स्थिति। फ्लैट देखने के लिए चार्ट में विंग चुनें।", "Loading collection data…": "संग्रह डेटा लोड हो रहा है…", "Total Collection": "कुल संग्रह", "Total Expenses": "कुल खर्च", "Balance": "शेष राशि", "NEXT PHASE": "अगला चरण", "Live Expense Dashboard": "लाइव खर्च डैशबोर्ड", "We can connect the committee's Google Sheet here and automatically display category-wise spending, total income, total expenses and balance.": "यहाँ समिति की Google Sheet जोड़कर श्रेणीवार खर्च, कुल आय, कुल खर्च और शेष राशि अपने आप दिखा सकते हैं।", "Google Sheets Ready": "Google Sheets के लिए तैयार",
      "Ganpati Bappa, Community & Celebration": "गणपति बप्पा, समुदाय और उत्सव", "Our festival is a shared celebration built by residents, volunteers and the Cultural Committee.": "हमारा उत्सव निवासियों, स्वयंसेवकों और सांस्कृतिक समिति का साझा आयोजन है।", "YOUR VOICE MATTERS": "आपकी राय महत्वपूर्ण है", "Suggestions & Feedback": "सुझाव और प्रतिक्रिया", "Have an idea to make the Sai Vista Ganpati festival better? Share it directly with the committee.": "साई विस्टा गणपति उत्सव को बेहतर बनाने का विचार है? उसे सीधे समिति के साथ साझा करें।", "Help shape the celebration": "उत्सव को बेहतर बनाएँ", "Your message opens in WhatsApp to Priyank so you can review it before sending. Please do not include payment details or other sensitive personal information.": "आपका संदेश प्रियंक को व्हाट्सऐप में खुलेगा ताकि भेजने से पहले आप उसे देख सकें। भुगतान विवरण या अन्य संवेदनशील व्यक्तिगत जानकारी शामिल न करें।", "Your suggestion": "आपका सुझाव", "Tell us what you would like to improve…": "बताइए कि आप क्या बेहतर करना चाहते हैं…", "Continue in WhatsApp ↗": "व्हाट्सऐप में आगे बढ़ें ↗", "Your suggestion is not stored on this website.": "आपका सुझाव इस वेबसाइट पर संग्रहीत नहीं होता।", "GET IN TOUCH": "संपर्क करें", "Contact & Coordinators": "संपर्क और समन्वयक", "If you have questions or need help with registrations, please reach out to the coordinators below.": "यदि आपके प्रश्न हैं या पंजीकरण में सहायता चाहिए, तो नीचे दिए समन्वयकों से संपर्क करें।", "Co-ordinator": "समन्वयक", "Website managed by Paresh Kale ·": "वेबसाइट प्रबंधन: परेश काले ·", "Registration Form": "पंजीकरण फ़ॉर्म", "Having trouble loading the form?": "फ़ॉर्म लोड करने में समस्या है?", "Open directly ↗": "सीधे खोलें ↗", "KURTA PAYMENT": "कुर्ता भुगतान", "Choose your UPI app": "अपना UPI ऐप चुनें", "Pay": "भुगतान करें", "to": "को", "for the Sai Vista Ganpati 2026 Kurta.": "साई विस्टा गणपति 2026 कुर्ते के लिए।", "UPI ID": "UPI आईडी", "Choose an installed UPI app": "इंस्टॉल किया हुआ UPI ऐप चुनें", "Copy UPI ID": "UPI आईडी कॉपी करें", "Your phone will show compatible UPI apps. Verify the recipient and amount before entering your UPI PIN.": "आपके फोन पर उपलब्ध UPI ऐप दिखाई देंगे। UPI PIN डालने से पहले प्राप्तकर्ता और राशि जाँचें।",
      "Open menu": "मेनू खोलें", "Close menu": "मेनू बंद करें", "Open notifications": "सूचनाएँ खोलें", "Install Sai Vista Ganpati app": "साई विस्टा गणपति ऐप इंस्टॉल करें", "Install festival app": "उत्सव ऐप इंस्टॉल करें", "Language": "भाषा", "English": "English", "Hindi": "हिंदी", "Marathi": "मराठी",
      "No special event scheduled for today — check the full schedule.": "आज कोई विशेष कार्यक्रम निर्धारित नहीं है — पूरा कार्यक्रम देखें।", "Starts in": "शुरू होने में", "Happening now!": "अभी चल रहा है!", "Page views: {count}": "पेज व्यू: {count}", "UPI ID copied. Open any UPI app and paste it to pay ₹300.": "UPI आईडी कॉपी हो गई। ₹300 भुगतान करने के लिए किसी भी UPI ऐप में पेस्ट करें।", "Copy is unavailable on this browser. Use karade.deepak1@ibl in your UPI app.": "इस ब्राउज़र में कॉपी उपलब्ध नहीं है। अपने UPI ऐप में karade.deepak1@ibl का उपयोग करें।"
    },
    mr: {
      "Home": "मुखपृष्ठ", "Schedule": "कार्यक्रम", "Registration": "नोंदणी", "Aarti": "आरती", "Accounts": "हिशेब", "Suggestions": "सूचना", "Register": "नोंदणी करा",
      "Notifications": "सूचना", "Mark all read": "सर्व वाचले म्हणून चिन्हांकित करा", "Turn on browser alerts": "ब्राउझर सूचना सुरू करा", "Alerts appear while this site is open.": "साइट सुरू असताना सूचना दिसतील।",
      "Kurta registration started!": "कुर्ता नोंदणी सुरू झाली आहे!", "Event Registration will start soon!": "कार्यक्रम नोंदणी लवकरच सुरू होईल!", "Stay tuned for more updates!": "अधिक अपडेटसाठी संपर्कात राहा!", "Loading today's event…": "आजचा कार्यक्रम लोड होत आहे…", "View today's schedule": "आजचा कार्यक्रम पहा",
      "SAI VISTA CULTURAL COMMITTEE": "साई व्हिस्टा सांस्कृतिक समिती", "Ganesh Festival": "गणेशोत्सव", "A celebration of devotion, culture, participation and community spirit.": "भक्ती, संस्कृती, सहभाग आणि सामुदायिक भावनेचा उत्सव।", "Explore Festival": "उत्सव पहा", "Register for Events": "कार्यक्रमांसाठी नोंदणी करा", "Festival begins in": "उत्सव सुरू होण्यास",
      "Full Festival Schedule": "संपूर्ण उत्सव कार्यक्रम", "Close": "बंद करा", "SAI VISTA GANPATI 2026": "साई व्हिस्टा गणपती 2026", "Ganpati Festival Kurta": "गणपती उत्सव कुर्ता", "Show your Ganpati spirit with the official Sai Vista Ganpati 2026 Kurta.": "अधिकृत साई व्हिस्टा गणपती 2026 कुर्त्यासह गणपती उत्सवाचा उत्साह साजरा करा।", "₹300 / Kurta": "₹300 / कुर्ता", "Sai Vista Ganpati 2026 Kurta": "साई व्हिस्टा गणपती 2026 कुर्ता", "If you are interested in purchasing the festival Kurta, please complete the registration form below.": "उत्सवाचा कुर्ता घ्यायचा असल्यास खालील नोंदणी फॉर्म भरा।", "Per Kurta": "प्रति कुर्ता", "Registration deadline": "नोंदणीची अंतिम तारीख", "Available sizes": "उपलब्ध आकार", "Last date to register": "नोंदणीची अंतिम तारीख", "8 September 2026": "8 सप्टेंबर 2026", "Interested in getting a Kurta?": "कुर्ता घ्यायचा आहे का?", "Select your interest and size in the official registration form. Available sizes are S, M, L and XL.": "अधिकृत नोंदणी फॉर्ममध्ये आपली पसंती आणि आकार निवडा. उपलब्ध आकार: S, M, L आणि XL।", "Important:": "महत्त्वाचे:", "Kurta cost is": "कुर्त्याची किंमत", "Registration must be completed by": "नोंदणी पूर्ण करण्याची अंतिम तारीख", "Register for Kurta ↗": "कुर्त्यासाठी नोंदणी करा ↗", "Pay ₹300 with UPI ↗": "UPI ने ₹300 भरा ↗", "Choose your preferred UPI app next. ₹300 is prefilled—please verify the recipient and amount before approving payment.": "पुढे आपला पसंतीचा UPI अॅप निवडा. ₹300 आधीच भरले आहेत—पेमेंटपूर्वी प्राप्तकर्ता आणि रक्कम तपासा।", "Registration is managed through Google Forms.": "नोंदणी Google Forms मधून केली जाते।",
      "LATEST UPDATE": "नवीनतम अपडेट", "Ganpati 2026 Event Schedule": "गणपती 2026 कार्यक्रम", "See the complete festival programme, important notes and registration information published by the Sai Vista Cultural Committee.": "साई व्हिस्टा सांस्कृतिक समितीने प्रसिद्ध केलेला संपूर्ण उत्सव कार्यक्रम, महत्त्वाच्या सूचना आणि नोंदणी माहिती पहा।", "View Full Schedule ↗": "संपूर्ण कार्यक्रम पहा ↗", "Tap to enlarge": "मोठे पाहण्यासाठी टॅप करा",
      "Festival Schedule": "उत्सव कार्यक्रम", "Events & activities": "कार्यक्रम आणि उपक्रम", "Event Registration": "कार्यक्रम नोंदणी", "Participate with us": "आमच्यासोबत सहभागी व्हा", "Aarti Nomination": "आरती नामनिर्देशन", "Choose your slot": "आपला स्लॉट निवडा", "Festival Accounts": "उत्सव हिशेब", "Transparent expenses": "पारदर्शक खर्च", "Ganpati Kurta": "गणपती कुर्ता", "Share a Suggestion": "सूचना द्या", "Help us make the festival better": "उत्सव अधिक चांगला बनवण्यात मदत करा", "Contact Us": "संपर्क करा", "Coordinators & website": "समन्वयक आणि वेबसाइट",
      "14 SEPTEMBER – 25 SEPTEMBER": "14 सप्टेंबर – 25 सप्टेंबर", "Ganpati 2026 Festival Schedule": "गणपती 2026 उत्सव कार्यक्रम", "Event dates and activities are based on the latest schedule shared by the Sai Vista Cultural Committee.": "कार्यक्रमाच्या तारखा आणि उपक्रम साई व्हिस्टा सांस्कृतिक समितीने शेअर केलेल्या नवीनतम कार्यक्रमावर आधारित आहेत।", "Add festival schedule to calendar": "उत्सव कार्यक्रम कॅलेंडरमध्ये जोडा", "Downloads an .ics calendar file. Events are added as all-day reminders.": ".ics कॅलेंडर फाइल डाउनलोड होईल. कार्यक्रम दिवसभराच्या स्मरणपत्रांसारखे जोडले जातील।", "All days": "सर्व दिवस", "Highlights": "ठळक कार्यक्रम", "Puja & Aarti": "पूजा आणि आरती", "Activities": "उपक्रम",
      "OPENING DAY • MONDAY": "उद्घाटन दिवस • सोमवार", "Miravnuk • Lezim (TBD) • Ganesh Sthapana": "मिरवणूक • लेझीम (निश्चित करायचे आहे) • गणेश स्थापना", "Miravnuk with music is planned between 3–7 PM. Residents are requested to plan decorations/work arrangements accordingly.": "संगीतासह मिरवणूक 3–7 PM दरम्यान नियोजित आहे. रहिवाशांनी सजावट/कामाची व्यवस्था त्यानुसार करावी।", "TUESDAY": "मंगळवार", "WEDNESDAY": "बुधवार", "THURSDAY": "गुरुवार", "FRIDAY": "शुक्रवार", "SATURDAY": "शनिवार", "SUNDAY": "रविवार", "Housie": "हौसी", "Community housie evening for Sai Vista residents.": "साई व्हिस्टा रहिवाशांसाठी सामुदायिक हौसी संध्याकाळ।", "Games": "खेळ", "Games and activities for residents.": "रहिवाशांसाठी खेळ आणि उपक्रम।", "Register →": "नोंदणी करा →", "SPECIAL EVENT • FRIDAY": "विशेष कार्यक्रम • शुक्रवार", "Bollywood Night 🎬": "बॉलिवूड नाईट 🎬", "Music, dance, performances and entertainment.": "संगीत, नृत्य, सादरीकरणे आणि मनोरंजन।", "Drawing Competition • Talent Show 1": "चित्रकला स्पर्धा • टॅलेंट शो 1", "Talent Show sessions are planned across the festival as announced by the committee.": "समितीच्या घोषणेनुसार टॅलेंट शोची सत्रे उत्सवभर आयोजित आहेत।", "Blood Donation • Treasure Hunt • Thali & Rangoli Competition • Fun N Fun Fair": "रक्तदान • ट्रेझर हंट • थाळी आणि रांगोळी स्पर्धा • फन एन फन फेअर", "A full community activity day with multiple participation events.": "अनेक सहभागाच्या कार्यक्रमांसह पूर्ण सामुदायिक उपक्रम दिवस।", "View registrations →": "नोंदणी पहा →", "Talent Show 2": "टॅलेंट शो 2", "Second Talent Show session.": "टॅलेंट शोचे दुसरे सत्र।", "Fancy Dress": "फॅन्सी ड्रेस", "Fancy Dress is planned as a separate event.": "फॅन्सी ड्रेस हा स्वतंत्र कार्यक्रम म्हणून नियोजित आहे।", "No activity currently planned": "सध्या कोणताही उपक्रम नियोजित नाही", "The programme will be updated if an activity is finalised.": "उपक्रम निश्चित झाल्यास कार्यक्रम अपडेट केला जाईल।", "PUJA • THURSDAY": "पूजा • गुरुवार", "Satyanarayan Puja & Mahaprasad": "सत्यनारायण पूजा आणि महाप्रसाद", "Dedicated Satyanarayan Puja and Mahaprasad programme.": "समर्पित सत्यनारायण पूजा आणि महाप्रसाद कार्यक्रम।", "Open Puja registration →": "पूजा नोंदणी उघडा →", "VISARJAN • FRIDAY": "विसर्जन • शुक्रवार", "Visarjan • Lezim (TBD) • DJ": "विसर्जन • लेझीम (निश्चित करायचे आहे) • DJ", "Visarjan programme with evening DJ as noted in the latest festival schedule.": "नवीनतम कार्यक्रमानुसार संध्याकाळच्या DJ सह विसर्जन कार्यक्रम।", "📌 Important Notes": "📌 महत्त्वाच्या सूचना",
      "PARTICIPATE": "सहभागी व्हा", "Registration & Festival Forms": "नोंदणी आणि उत्सव फॉर्म", "Everything important is grouped in one place. Forms currently open inside a simple website modal so residents do not have to navigate away first.": "सर्व महत्त्वाचे फॉर्म एका ठिकाणी आहेत. सध्या फॉर्म वेबसाइटमध्येच उघडतात, त्यामुळे रहिवाशांना लगेच दुसरीकडे जावे लागत नाही।", "MAIN REGISTRATION": "मुख्य नोंदणी", "All Event Registration": "सर्व कार्यक्रम नोंदणी", "Use the common Sai Vista event registration form for festival activities.": "उत्सव उपक्रमांसाठी सामान्य साई व्हिस्टा नोंदणी फॉर्म वापरा।", "Open Registration": "नोंदणी उघडा", "Registration currently disabled": "नोंदणी सध्या बंद आहे", "PUJA": "पूजा", "Satyanarayan Pooja": "सत्यनारायण पूजा", "Register for the Satyanarayan Pooja using the dedicated form.": "समर्पित फॉर्मद्वारे सत्यनारायण पूजेसाठी नोंदणी करा।", "Open Form": "फॉर्म उघडा", "SPECIAL EVENT": "विशेष कार्यक्रम", "Participation and entry registration for Bollywood Night.": "बॉलिवूड नाईटसाठी सहभाग आणि प्रवेश नोंदणी।", "PRASAD": "प्रसाद", "Satyanarayan Prasad Availability": "सत्यनारायण प्रसाद उपलब्धता", "Confirm availability / requirement for Satyanarayan Prasad.": "सत्यनारायण प्रसादाची उपलब्धता/गरज निश्चित करा।", "FUN FAIR": "फन फेअर", "Fun Fair Stall Entry": "फन फेअर स्टॉल प्रवेश", "Submit your Fun Fair stall event entry through the dedicated form.": "समर्पित फॉर्मद्वारे आपल्या फन फेअर स्टॉलची नोंद पाठवा।", "KURTA": "कुर्ता", "Kurta / Traditional Wear Registration": "कुर्ता / पारंपरिक पोशाख नोंदणी", "Register for kurta orders / collection. This form opens in a dialog on the same page.": "कुर्ता ऑर्डर/कलेक्शनसाठी नोंदणी करा. हा फॉर्म याच पानावर उघडतो।", "Open Kurta Form": "कुर्ता फॉर्म उघडा",
      "AUSPICIOUS MOMENT": "शुभ प्रसंग", "🪔 Ganesh Aarti Nomination": "🪔 गणेश आरती नामनिर्देशन", "Nominate yourself or your family for Ganesh Bappa's Aarti at Sai Vista.": "साई व्हिस्टामधील गणेश बाप्पाच्या आरतीसाठी स्वतःचे किंवा कुटुंबाचे नाव नोंदवा।", "Full Name *": "पूर्ण नाव *", "Flat Number *": "फ्लॅट क्रमांक *", "Select Flat Number": "फ्लॅट क्रमांक निवडा", "Wing *": "विंग *", "Select Wing": "विंग निवडा", "WhatsApp Number *": "व्हॉट्सअॅप क्रमांक *", "Enter 10 digits without country code.": "देश कोडशिवाय 10 अंक टाका।", "Select Aarti Date *": "आरतीची तारीख निवडा *", "Choose a date between 15 Sep and 24 Sep 2026.": "15 सप्टेंबर ते 24 सप्टेंबर 2026 मधील तारीख निवडा।", "Select Slot *": "स्लॉट निवडा *", "Morning (8 AM)": "सकाळ (8 AM)", "Evening (7:30 PM)": "संध्याकाळ (7:30 PM)", "Select a date and slot to see current registrations.": "सध्याची नोंदणी पाहण्यासाठी तारीख आणि स्लॉट निवडा।", "I will bring my own pooja thali and prasad": "मी माझे पूजेचे ताट आणि प्रसाद आणेन", "Submit Aarti Nomination": "आरती नामनिर्देशन पाठवा", "Thank you for your nomination!": "आपल्या नामनिर्देशनाबद्दल धन्यवाद!", "ℹ️ Your nomination is sent to the Sai Vista festival registration system for coordination.": "ℹ️ आपले नामनिर्देशन समन्वयासाठी साई व्हिस्टा उत्सव नोंदणी प्रणालीकडे पाठवले आहे।", "LIMITED REGISTRATION": "मर्यादित नोंदणी",
      "TRANSPARENCY": "पारदर्शकता", "Festival Collection Dashboard": "उत्सव संकलन डॅशबोर्ड", "Live resident contribution status, grouped by wing. Select a wing in the chart to view its flats.": "विंगनुसार रहिवाशांच्या योगदानाची स्थिती. फ्लॅट पाहण्यासाठी चार्टमध्ये विंग निवडा।", "Loading collection data…": "संकलन डेटा लोड होत आहे…", "Total Collection": "एकूण संकलन", "Total Expenses": "एकूण खर्च", "Balance": "शिल्लक", "NEXT PHASE": "पुढचा टप्पा", "Live Expense Dashboard": "थेट खर्च डॅशबोर्ड", "We can connect the committee's Google Sheet here and automatically display category-wise spending, total income, total expenses and balance.": "समितीची Google Sheet येथे जोडून श्रेणीनुसार खर्च, एकूण उत्पन्न, एकूण खर्च आणि शिल्लक आपोआप दाखवता येईल।", "Google Sheets Ready": "Google Sheets साठी तयार",
      "Ganpati Bappa, Community & Celebration": "गणपती बाप्पा, समुदाय आणि उत्सव", "Our festival is a shared celebration built by residents, volunteers and the Cultural Committee.": "आपला उत्सव हा रहिवासी, स्वयंसेवक आणि सांस्कृतिक समितीने घडवलेला सामूहिक सोहळा आहे।", "YOUR VOICE MATTERS": "तुमचे मत महत्त्वाचे आहे", "Suggestions & Feedback": "सूचना आणि अभिप्राय", "Have an idea to make the Sai Vista Ganpati festival better? Share it directly with the committee.": "साई व्हिस्टा गणपती उत्सव अधिक चांगला करण्याची कल्पना आहे का? ती थेट समितीला सांगा।", "Help shape the celebration": "उत्सव अधिक चांगला बनवा", "Your message opens in WhatsApp to Priyank so you can review it before sending. Please do not include payment details or other sensitive personal information.": "आपला संदेश प्रियंकच्या व्हॉट्सअॅपमध्ये उघडेल, त्यामुळे पाठवण्यापूर्वी आपण तो तपासू शकता. पेमेंट तपशील किंवा इतर संवेदनशील वैयक्तिक माहिती टाकू नका।", "Your suggestion": "आपली सूचना", "Tell us what you would like to improve…": "आपण काय सुधारू इच्छिता ते सांगा…", "Continue in WhatsApp ↗": "व्हॉट्सअॅपमध्ये पुढे जा ↗", "Your suggestion is not stored on this website.": "आपली सूचना या वेबसाइटवर साठवली जात नाही।", "GET IN TOUCH": "संपर्क करा", "Contact & Coordinators": "संपर्क आणि समन्वयक", "If you have questions or need help with registrations, please reach out to the coordinators below.": "प्रश्न असल्यास किंवा नोंदणीत मदत हवी असल्यास खालील समन्वयकांशी संपर्क करा।", "Co-ordinator": "समन्वयक", "Website managed by Paresh Kale ·": "वेबसाइट व्यवस्थापन: परेश काले ·", "Registration Form": "नोंदणी फॉर्म", "Having trouble loading the form?": "फॉर्म लोड करण्यात अडचण येत आहे का?", "Open directly ↗": "थेट उघडा ↗", "KURTA PAYMENT": "कुर्ता पेमेंट", "Choose your UPI app": "आपला UPI अॅप निवडा", "Pay": "भरा", "to": "यांना", "for the Sai Vista Ganpati 2026 Kurta.": "साई व्हिस्टा गणपती 2026 कुर्त्यासाठी।", "UPI ID": "UPI आयडी", "Choose an installed UPI app": "स्थापित UPI अॅप निवडा", "Copy UPI ID": "UPI आयडी कॉपी करा", "Your phone will show compatible UPI apps. Verify the recipient and amount before entering your UPI PIN.": "आपल्या फोनवर उपलब्ध UPI अॅप दिसतील. UPI PIN टाकण्यापूर्वी प्राप्तकर्ता आणि रक्कम तपासा।",
      "Open menu": "मेनू उघडा", "Close menu": "मेनू बंद करा", "Open notifications": "सूचना उघडा", "Install Sai Vista Ganpati app": "साई व्हिस्टा गणपती अॅप स्थापित करा", "Install festival app": "उत्सव अॅप स्थापित करा", "Language": "भाषा", "English": "English", "Hindi": "हिंदी", "Marathi": "मराठी",
      "No special event scheduled for today — check the full schedule.": "आज कोणताही विशेष कार्यक्रम नियोजित नाही — संपूर्ण कार्यक्रम पहा।", "Starts in": "सुरू होण्यास", "Happening now!": "आत्ता सुरू आहे!", "Page views: {count}": "पृष्ठ पाहणी: {count}", "UPI ID copied. Open any UPI app and paste it to pay ₹300.": "UPI आयडी कॉपी झाला. ₹300 भरण्यासाठी कोणत्याही UPI अॅपमध्ये पेस्ट करा।", "Copy is unavailable on this browser. Use karade.deepak1@ibl in your UPI app.": "या ब्राउझरमध्ये कॉपी उपलब्ध नाही. आपल्या UPI अॅपमध्ये karade.deepak1@ibl वापरा।"
    }
  };

  Object.assign(translations.hi, {
    "5 Sep — Janmashtami Celebration at Sai Vista Ground Floor Lawn (6:00 PM – 10:00 PM IST). Please join us for the celebration!": "5 सितम्बर — साई विस्टा ग्राउंड फ्लोर लॉन में जन्माष्टमी समारोह (6:00 PM – 10:00 PM IST)। कृपया समारोह में शामिल हों!",
    "14 Sep — Opening Day: Miravnuk, Lezim and Ganesh Sthapana (3–7 PM).": "14 सितम्बर — उद्घाटन दिवस: मिरवणूक, लेझीम और गणेश स्थापना (3–7 PM)।",
    "15 Sep — Housie evening for residents.": "15 सितम्बर — निवासियों के लिए हाउज़ी शाम।",
    "16 Sep — Games and activities. Register for events.": "16 सितम्बर — खेल और गतिविधियाँ। कार्यक्रमों के लिए पंजीकरण करें।",
    "17 Sep — Games and community activities.": "17 सितम्बर — खेल और सामुदायिक गतिविधियाँ।",
    "18 Sep — Bollywood Night (special event).": "18 सितम्बर — बॉलीवुड नाइट (विशेष कार्यक्रम)।",
    "19 Sep — Drawing Competition & Talent Show (session 1).": "19 सितम्बर — चित्रकला प्रतियोगिता और टैलेंट शो (सत्र 1)।",
    "20 Sep — Blood donation, Treasure Hunt, Thali & Rangoli competition.": "20 सितम्बर — रक्तदान, ट्रेज़र हंट, थाली और रंगोली प्रतियोगिता।",
    "21 Sep — Talent Show (session 2).": "21 सितम्बर — टैलेंट शो (सत्र 2)।",
    "22 Sep — Fancy Dress event.": "22 सितम्बर — फैंसी ड्रेस कार्यक्रम।",
    "23 Sep — No activity planned (schedule may be updated).": "23 सितम्बर — कोई गतिविधि नियोजित नहीं है (कार्यक्रम अपडेट हो सकता है)।",
    "24 Sep — Satyanarayan Puja & Mahaprasad.": "24 सितम्बर — सत्यनारायण पूजा और महाप्रसाद।",
    "25 Sep — Visarjan, Lezim and evening DJ.": "25 सितम्बर — विसर्जन, लेझीम और शाम का DJ।",
    "Aarti nominations are open": "आरती नामांकन खुले हैं", "Choose your preferred morning or evening Aarti slot for 15–24 September.": "15–24 सितम्बर के लिए अपना पसंदीदा सुबह या शाम का आरती स्लॉट चुनें।", "View Aarti slots": "आरती स्लॉट देखें", "Plan your Aarti in advance": "अपनी आरती पहले से तय करें", "Slots have limited capacity. Submit your nomination early to reserve your preference.": "स्लॉट की क्षमता सीमित है। अपनी पसंद के लिए जल्दी नामांकन भेजें।", "Nominate for Aarti": "आरती के लिए नामांकन करें",
    "Browser alerts are not supported on this device.": "इस डिवाइस पर ब्राउज़र अलर्ट समर्थित नहीं हैं।", "Browser alerts are enabled while this page is open.": "यह पेज खुला होने पर ब्राउज़र अलर्ट चालू हैं।", "Browser alerts are blocked in your browser settings.": "आपकी ब्राउज़र सेटिंग में अलर्ट ब्लॉक हैं।", "Sai Vista Aarti updates": "साई विस्टा आरती अपडेट", "Aarti notifications are enabled while this page is open.": "यह पेज खुला होने पर आरती सूचनाएँ चालू हैं।"
  });
  Object.assign(translations.mr, {
    "5 Sep — Janmashtami Celebration at Sai Vista Ground Floor Lawn (6:00 PM – 10:00 PM IST). Please join us for the celebration!": "5 सप्टेंबर — साई व्हिस्टा ग्राउंड फ्लोअर लॉनमध्ये जन्माष्टमी उत्सव (6:00 PM – 10:00 PM IST)। कृपया उत्सवात सहभागी व्हा!",
    "14 Sep — Opening Day: Miravnuk, Lezim and Ganesh Sthapana (3–7 PM).": "14 सप्टेंबर — उद्घाटन दिवस: मिरवणूक, लेझीम आणि गणेश स्थापना (3–7 PM)।",
    "15 Sep — Housie evening for residents.": "15 सप्टेंबर — रहिवाशांसाठी हौसी संध्याकाळ।",
    "16 Sep — Games and activities. Register for events.": "16 सप्टेंबर — खेळ आणि उपक्रम. कार्यक्रमांसाठी नोंदणी करा।",
    "17 Sep — Games and community activities.": "17 सप्टेंबर — खेळ आणि सामुदायिक उपक्रम।",
    "18 Sep — Bollywood Night (special event).": "18 सप्टेंबर — बॉलिवूड नाईट (विशेष कार्यक्रम)।",
    "19 Sep — Drawing Competition & Talent Show (session 1).": "19 सप्टेंबर — चित्रकला स्पर्धा आणि टॅलेंट शो (सत्र 1)।",
    "20 Sep — Blood donation, Treasure Hunt, Thali & Rangoli competition.": "20 सप्टेंबर — रक्तदान, ट्रेझर हंट, थाळी आणि रांगोळी स्पर्धा।",
    "21 Sep — Talent Show (session 2).": "21 सप्टेंबर — टॅलेंट शो (सत्र 2)।",
    "22 Sep — Fancy Dress event.": "22 सप्टेंबर — फॅन्सी ड्रेस कार्यक्रम।",
    "23 Sep — No activity planned (schedule may be updated).": "23 सप्टेंबर — कोणताही उपक्रम नियोजित नाही (कार्यक्रम अपडेट होऊ शकतो)।",
    "24 Sep — Satyanarayan Puja & Mahaprasad.": "24 सप्टेंबर — सत्यनारायण पूजा आणि महाप्रसाद।",
    "25 Sep — Visarjan, Lezim and evening DJ.": "25 सप्टेंबर — विसर्जन, लेझीम आणि संध्याकाळचा DJ।",
    "Aarti nominations are open": "आरती नामनिर्देशन खुले आहेत", "Choose your preferred morning or evening Aarti slot for 15–24 September.": "15–24 सप्टेंबरसाठी आपला पसंतीचा सकाळ किंवा संध्याकाळचा आरती स्लॉट निवडा।", "View Aarti slots": "आरती स्लॉट पहा", "Plan your Aarti in advance": "आरतीचे नियोजन आधी करा", "Slots have limited capacity. Submit your nomination early to reserve your preference.": "स्लॉटची क्षमता मर्यादित आहे. पसंती राखण्यासाठी लवकर नामनिर्देशन पाठवा।", "Nominate for Aarti": "आरतीसाठी नामनिर्देशन करा",
    "Browser alerts are not supported on this device.": "या डिव्हाइसवर ब्राउझर सूचना समर्थित नाहीत।", "Browser alerts are enabled while this page is open.": "हे पान उघडे असताना ब्राउझर सूचना सुरू आहेत।", "Browser alerts are blocked in your browser settings.": "आपल्या ब्राउझर सेटिंगमध्ये सूचना ब्लॉक आहेत।", "Sai Vista Aarti updates": "साई व्हिस्टा आरती अपडेट", "Aarti notifications are enabled while this page is open.": "हे पान उघडे असताना आरती सूचना सुरू आहेत।"
  });

  Object.assign(translations.hi, {
    "Sai Vista Registration Form": "साई विस्टा पंजीकरण फ़ॉर्म", "Please select an Aarti date between {min} and {max}.": "कृपया {min} और {max} के बीच की आरती तिथि चुनें।", "Now choose Morning or Evening to check availability.": "उपलब्धता देखने के लिए अब सुबह या शाम चुनें।", "Please select an Aarti date first.": "कृपया पहले आरती की तिथि चुनें।", "⏳ Checking current registrations...": "⏳ वर्तमान पंजीकरण देखे जा रहे हैं...", "{count} / {capacity} registered": "{count} / {capacity} पंजीकृत", "{count} slot available": "{count} स्लॉट उपलब्ध", "{count} slots available": "{count} स्लॉट उपलब्ध", "This slot is currently full.": "यह स्लॉट अभी पूरा भर चुका है।", "Availability could not be loaded right now. Please submit and the committee can verify the slot.": "उपलब्धता अभी लोड नहीं हो सकी। आप नामांकन भेजें, समिति स्लॉट की पुष्टि कर सकती है।", "Please fill all required fields correctly and select an Aarti slot.": "कृपया सभी आवश्यक जानकारी सही भरें और आरती स्लॉट चुनें।", "Submitting...": "भेजा जा रहा है...", "Your nomination has been successfully registered.": "आपका नामांकन सफलतापूर्वक पंजीकृत हो गया है।", "Open WhatsApp to message the admin →": "एडमिन को संदेश भेजने के लिए WhatsApp खोलें →", "There was a problem submitting the nomination. Please try again.": "नामांकन भेजने में समस्या हुई। कृपया फिर प्रयास करें।",
    "Collection data could not be loaded right now. Please refresh in a moment.": "संग्रह डेटा अभी लोड नहीं हो सका। कृपया थोड़ी देर में पेज रिफ्रेश करें।", "Total flats": "कुल फ्लैट", "Amount received": "प्राप्त राशि", "Amount pending": "लंबित राशि", "Collection rate": "संग्रह दर", "Payments by Wing": "विंग अनुसार भुगतान", "Green is paid; orange is pending. Click a wing to drill down.": "हरा भुगतान हो चुका है; नारंगी लंबित है। विवरण देखने के लिए विंग चुनें।", "Overall payment status": "कुल भुगतान स्थिति", "Only “Yes” payments count toward money received.": "केवल “हाँ” भुगतान ही प्राप्त राशि में गिने जाते हैं।", "paid": "भुगतान", "Paid:": "भुगतान:", "Pending:": "लंबित:", "All flats": "सभी फ्लैट", "All wings": "सभी विंग", "Filter payment status": "भुगतान स्थिति फ़िल्टर करें", "All statuses": "सभी स्थितियाँ", "Paid only": "केवल भुगतान", "Pending only": "केवल लंबित", "Sort flats": "फ्लैट क्रमबद्ध करें", "Sort: Flat number": "क्रम: फ्लैट नंबर", "Sort: Payment status": "क्रम: भुगतान स्थिति", "Sort: Amount": "क्रम: राशि", "Wing": "विंग", "Flat": "फ्लैट", "Status": "स्थिति", "Amount": "राशि", "Paid": "भुगतान", "Not paid": "भुगतान नहीं", "No flats match this filter.": "इस फ़िल्टर से कोई फ्लैट नहीं मिला।", "Source: live Sai Vista contribution sheet · refreshed when the page loads": "स्रोत: लाइव साई विस्टा योगदान शीट · पेज लोड होने पर ताज़ा", "Wing {wing}": "विंग {wing}", "Show Wing {wing} flats": "विंग {wing} के फ्लैट दिखाएँ", "Wing {wing} flats": "विंग {wing} के फ्लैट", "{paid} paid / {total}": "{paid} भुगतान / {total}"
  });
  Object.assign(translations.mr, {
    "Sai Vista Registration Form": "साई व्हिस्टा नोंदणी फॉर्म", "Please select an Aarti date between {min} and {max}.": "कृपया {min} आणि {max} दरम्यानची आरती तारीख निवडा।", "Now choose Morning or Evening to check availability.": "उपलब्धता पाहण्यासाठी आता सकाळ किंवा संध्याकाळ निवडा।", "Please select an Aarti date first.": "कृपया आधी आरतीची तारीख निवडा।", "⏳ Checking current registrations...": "⏳ सध्याची नोंदणी तपासत आहोत...", "{count} / {capacity} registered": "{count} / {capacity} नोंदणीकृत", "{count} slot available": "{count} स्लॉट उपलब्ध", "{count} slots available": "{count} स्लॉट उपलब्ध", "This slot is currently full.": "हा स्लॉट सध्या पूर्ण भरला आहे।", "Availability could not be loaded right now. Please submit and the committee can verify the slot.": "उपलब्धता सध्या लोड झाली नाही. आपण नामनिर्देशन पाठवा; समिती स्लॉटची पडताळणी करू शकते।", "Please fill all required fields correctly and select an Aarti slot.": "कृपया सर्व आवश्यक माहिती योग्य भरा आणि आरती स्लॉट निवडा।", "Submitting...": "पाठवत आहोत...", "Your nomination has been successfully registered.": "आपले नामनिर्देशन यशस्वीरीत्या नोंदवले गेले आहे।", "Open WhatsApp to message the admin →": "प्रशासकाला संदेश पाठवण्यासाठी WhatsApp उघडा →", "There was a problem submitting the nomination. Please try again.": "नामनिर्देशन पाठवताना अडचण आली. कृपया पुन्हा प्रयत्न करा।",
    "Collection data could not be loaded right now. Please refresh in a moment.": "संकलन डेटा सध्या लोड झाला नाही. कृपया थोड्या वेळाने पेज रिफ्रेश करा।", "Total flats": "एकूण फ्लॅट", "Amount received": "मिळालेली रक्कम", "Amount pending": "प्रलंबित रक्कम", "Collection rate": "संकलन दर", "Payments by Wing": "विंगनुसार देयके", "Green is paid; orange is pending. Click a wing to drill down.": "हिरवा म्हणजे भरलेले; नारिंगी म्हणजे प्रलंबित. तपशील पाहण्यासाठी विंग निवडा।", "Overall payment status": "एकूण पेमेंट स्थिती", "Only “Yes” payments count toward money received.": "फक्त “होय” पेमेंट मिळालेल्या रकमेत मोजली जातात।", "paid": "भरले", "Paid:": "भरले:", "Pending:": "प्रलंबित:", "All flats": "सर्व फ्लॅट", "All wings": "सर्व विंग", "Filter payment status": "पेमेंट स्थिती फिल्टर करा", "All statuses": "सर्व स्थिती", "Paid only": "फक्त भरलेले", "Pending only": "फक्त प्रलंबित", "Sort flats": "फ्लॅट क्रम लावा", "Sort: Flat number": "क्रम: फ्लॅट क्रमांक", "Sort: Payment status": "क्रम: पेमेंट स्थिती", "Sort: Amount": "क्रम: रक्कम", "Wing": "विंग", "Flat": "फ्लॅट", "Status": "स्थिती", "Amount": "रक्कम", "Paid": "भरले", "Not paid": "न भरलेले", "No flats match this filter.": "या फिल्टरशी जुळणारे फ्लॅट नाहीत।", "Source: live Sai Vista contribution sheet · refreshed when the page loads": "स्रोत: लाईव्ह साई व्हिस्टा योगदान शीट · पेज लोड झाल्यावर अद्ययावत", "Wing {wing}": "विंग {wing}", "Show Wing {wing} flats": "विंग {wing} चे फ्लॅट दाखवा", "Wing {wing} flats": "विंग {wing} चे फ्लॅट", "{paid} paid / {total}": "{paid} भरले / {total}"
  });

  Object.assign(translations.hi, {
    "Skip to main content": "मुख्य सामग्री पर जाएँ", "HAPPENING TODAY": "आज का कार्यक्रम", "Today at Sai Vista": "आज साई विस्टा में", "Loading today’s details…": "आज की जानकारी लोड हो रही है…", "Loading today’s event…": "आज का कार्यक्रम लोड हो रहा है…", "View today’s schedule": "आज का कार्यक्रम देखें", "Close today’s update": "आज का अपडेट बंद करें", "Time: {time} · Location: {place}": "समय: {time} · स्थान: {place}", "Please check the full schedule for upcoming activities.": "आने वाली गतिविधियों के लिए पूरा कार्यक्रम देखें।", "Sai Vista Ground Floor Lawn": "साई विस्टा ग्राउंड फ्लोर लॉन", "Sai Vista, Rahatani": "साई विस्टा, रहाटणी", "Evening": "शाम", "As scheduled": "निर्धारित समय अनुसार", "A complete written schedule is provided below for easy reading and screen-reader access.": "आसान पढ़ने और स्क्रीन-रीडर उपयोग के लिए पूरा लिखित कार्यक्रम नीचे दिया गया है।",
    "COMMITTEE UPDATES": "समिति अपडेट", "Latest Updates": "नवीनतम अपडेट", "Important festival changes and reminders from the Sai Vista Cultural Committee.": "साई विस्टा सांस्कृतिक समिति से महत्वपूर्ण बदलाव और रिमाइंडर।", "Loading committee updates…": "समिति अपडेट लोड हो रहे हैं…", "No committee updates have been published yet.": "अभी कोई समिति अपडेट प्रकाशित नहीं हुआ है।", "Registration": "पंजीकरण", "Kurta registration is open": "कुर्ता पंजीकरण खुला है", "Sizes S through XL are available. Please register by 8 September.": "S से XL तक साइज़ उपलब्ध हैं। कृपया 8 सितंबर तक पंजीकरण करें।", "View Kurta details": "कुर्ता विवरण देखें", "Aarti": "आरती", "Choose a morning or evening Aarti slot for 15–24 September.": "15–24 सितंबर के लिए सुबह या शाम का आरती स्लॉट चुनें।", "Schedule": "कार्यक्रम", "Festival schedule is available": "उत्सव कार्यक्रम उपलब्ध है", "Check the written schedule for event timings, registration links and important notes.": "कार्यक्रम के समय, पंजीकरण लिंक और महत्वपूर्ण सूचनाओं के लिए लिखित कार्यक्रम देखें।", "View schedule": "कार्यक्रम देखें", "Update": "अपडेट", "View update": "अपडेट देखें",
    "Festival Finance Overview": "उत्सव वित्तीय विवरण", "Committee-approved aggregate collection and expense totals. Individual resident or flat payment information is never displayed here.": "समिति द्वारा अनुमोदित कुल संग्रह और खर्च। व्यक्तिगत निवासी या फ्लैट का भुगतान विवरण यहाँ कभी प्रदर्शित नहीं होता।", "Loading financial overview…": "वित्तीय विवरण लोड हो रहा है…", "For privacy, this page publishes only verified category totals and committee-approved receipt links.": "गोपनीयता के लिए, यह पेज केवल सत्यापित श्रेणी कुल और समिति-अनुमोदित रसीद लिंक प्रकाशित करता है।", "Not published": "प्रकाशित नहीं", "Pending committee verification": "समिति सत्यापन लंबित", "LAST UPDATED": "अंतिम अपडेट", "Verified on: {date}": "सत्यापित तिथि: {date}", "Expenses by category": "श्रेणी अनुसार खर्च", "Verified category totals will be published here after committee approval.": "समिति अनुमोदन के बाद सत्यापित श्रेणी कुल यहाँ प्रकाशित किए जाएंगे।", "Published bills and receipts": "प्रकाशित बिल और रसीदें"
  });
  Object.assign(translations.mr, {
    "Skip to main content": "मुख्य मजकुराकडे जा", "HAPPENING TODAY": "आजचा कार्यक्रम", "Today at Sai Vista": "आज साई व्हिस्टामध्ये", "Loading today’s details…": "आजची माहिती लोड होत आहे…", "Loading today’s event…": "आजचा कार्यक्रम लोड होत आहे…", "View today’s schedule": "आजचा कार्यक्रम पहा", "Close today’s update": "आजचे अपडेट बंद करा", "Time: {time} · Location: {place}": "वेळ: {time} · ठिकाण: {place}", "Please check the full schedule for upcoming activities.": "पुढील उपक्रमांसाठी संपूर्ण कार्यक्रम पहा।", "Sai Vista Ground Floor Lawn": "साई व्हिस्टा ग्राउंड फ्लोअर लॉन", "Sai Vista, Rahatani": "साई व्हिस्टा, रहाटणी", "Evening": "संध्याकाळ", "As scheduled": "नियोजित वेळेनुसार", "A complete written schedule is provided below for easy reading and screen-reader access.": "सुलभ वाचन आणि स्क्रीन-रीडर वापरासाठी संपूर्ण लिखित कार्यक्रम खाली दिला आहे।",
    "COMMITTEE UPDATES": "समिती अपडेट", "Latest Updates": "नवीनतम अपडेट", "Important festival changes and reminders from the Sai Vista Cultural Committee.": "साई व्हिस्टा सांस्कृतिक समितीकडून महत्त्वाचे बदल आणि आठवणी।", "Loading committee updates…": "समिती अपडेट लोड होत आहेत…", "No committee updates have been published yet.": "अद्याप कोणतेही समिती अपडेट प्रकाशित झालेले नाही।", "Registration": "नोंदणी", "Kurta registration is open": "कुर्ता नोंदणी खुली आहे", "Sizes S through XL are available. Please register by 8 September.": "S ते XL आकार उपलब्ध आहेत. कृपया 8 सप्टेंबरपर्यंत नोंदणी करा।", "View Kurta details": "कुर्त्याचा तपशील पहा", "Aarti": "आरती", "Choose a morning or evening Aarti slot for 15–24 September.": "15–24 सप्टेंबरसाठी सकाळ किंवा संध्याकाळचा आरती स्लॉट निवडा।", "Schedule": "कार्यक्रम", "Festival schedule is available": "उत्सव कार्यक्रम उपलब्ध आहे", "Check the written schedule for event timings, registration links and important notes.": "कार्यक्रमाची वेळ, नोंदणी लिंक आणि महत्त्वाच्या सूचनांसाठी लिखित कार्यक्रम पहा।", "View schedule": "कार्यक्रम पहा", "Update": "अपडेट", "View update": "अपडेट पहा",
    "Festival Finance Overview": "उत्सव आर्थिक आढावा", "Committee-approved aggregate collection and expense totals. Individual resident or flat payment information is never displayed here.": "समितीने मंजूर केलेले एकत्रित संकलन आणि खर्च. वैयक्तिक रहिवासी किंवा फ्लॅटचे पेमेंट तपशील येथे कधीही दाखवले जात नाहीत।", "Loading financial overview…": "आर्थिक आढावा लोड होत आहे…", "For privacy, this page publishes only verified category totals and committee-approved receipt links.": "गोपनीयतेसाठी, हे पान केवळ सत्यापित श्रेणी एकूण आणि समितीने मंजूर केलेल्या रसीद लिंक प्रकाशित करते।", "Not published": "प्रकाशित नाही", "Pending committee verification": "समिती पडताळणी प्रलंबित", "LAST UPDATED": "शेवटचा अपडेट", "Verified on: {date}": "पडताळणी तारीख: {date}", "Expenses by category": "श्रेणीनुसार खर्च", "Verified category totals will be published here after committee approval.": "समितीच्या मंजुरीनंतर सत्यापित श्रेणी एकूण येथे प्रकाशित केले जातील।", "Published bills and receipts": "प्रकाशित बिले आणि रसीदा"
  });

  const locales = { en: "en-IN", hi: "hi-IN", mr: "mr-IN" };
  const originalText = new WeakMap();
  const originalAttributes = new WeakMap();
  let language = "en";

  const interpolate = (value, values = {}) => String(value).replace(/\{(\w+)\}/g, (_match, key) => values[key] ?? `{${key}}`);
  const t = (key, values) => interpolate(translations[language]?.[key] || key, values);
  const normalise = (value) => String(value).replace(/\s+/g, " ").trim();

  const translateDocument = () => {
    document.documentElement.lang = language;
    document.title = language === "hi" ? "साई विस्टा गणेश उत्सव 2026" : language === "mr" ? "साई व्हिस्टा गणेशोत्सव 2026" : "Sai Vista Ganesh Festival 2026";
    document.querySelectorAll("body *").forEach((element) => {
      if (["SCRIPT", "STYLE", "SVG", "PATH"].includes(element.tagName)) return;
      const attributes = ["aria-label", "title", "placeholder", "alt"];
      if (!originalAttributes.has(element)) {
        originalAttributes.set(element, Object.fromEntries(attributes.filter((name) => element.hasAttribute(name)).map((name) => [name, element.getAttribute(name)])));
      }
      const saved = originalAttributes.get(element);
      Object.entries(saved).forEach(([name, value]) => {
        const translated = t(normalise(value));
        element.setAttribute(name, translated === normalise(value) ? value : translated);
      });
    });

    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
      acceptNode(node) {
        const parent = node.parentElement;
        if (!parent || ["SCRIPT", "STYLE", "SVG"].includes(parent.tagName)) return NodeFilter.FILTER_REJECT;
        return normalise(node.nodeValue) ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT;
      }
    });
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach((node) => {
      if (!originalText.has(node)) originalText.set(node, node.nodeValue);
      const source = originalText.get(node);
      const key = normalise(source);
      const translated = t(key);
      if (translated === key) {
        node.nodeValue = source;
        return;
      }
      const leading = source.match(/^\s*/)?.[0] || "";
      const trailing = source.match(/\s*$/)?.[0] || "";
      node.nodeValue = `${leading}${translated}${trailing}`;
    });
    document.querySelectorAll("[data-language]").forEach((button) => {
      const selected = button.dataset.language === language;
      button.classList.toggle("is-active", selected);
      button.setAttribute("aria-pressed", String(selected));
    });
  };

  const setLanguage = (nextLanguage, announce = true) => {
    language = Object.hasOwn(locales, nextLanguage) ? nextLanguage : "en";
    try { localStorage.setItem("saiVistaLanguage", language); } catch (_) { /* Browser storage can be unavailable. */ }
    translateDocument();
    if (announce) document.dispatchEvent(new CustomEvent("sai-vista-language-change", { detail: { language } }));
  };

  window.SaiVistaI18n = {
    t,
    get language() { return language; },
    get locale() { return locales[language]; },
    setLanguage,
    refresh: translateDocument
  };

  document.addEventListener("DOMContentLoaded", () => {
    try { language = Object.hasOwn(locales, localStorage.getItem("saiVistaLanguage")) ? localStorage.getItem("saiVistaLanguage") : "en"; } catch (_) { language = "en"; }
    document.querySelectorAll("[data-language]").forEach((button) => button.addEventListener("click", () => setLanguage(button.dataset.language)));
    translateDocument();
  });
})();
